# _config.yml

# Basic settings
title: FastiShare
description: Fast. File Sharing
theme: jekyll-theme-cayman
show_downloads: false

# Site metadata
url: "https://flagodna-developer.github.io/FastiShare"
author: "FlagoDNA"

# SEO & Social sharing
og_image: "/assets/fastishare-preview.png"  # Needs to be a full URL or hosted on your GitHub Pages
twitter_card: summary_large_image

# Favicon
favicon: "/assets/favicon.ico"
