# _config.yml

# Basic settings
title: FastiShare
description: Fast. File Sharing
theme: jekyll-theme-cayman
show_downloads: false

# Site metadata
url: "https://flagodna-developer.github.io/FastiShare"
author: "FlagoDNA"

# SEO & Social sharing
og_image: "https://flagodna-developer.github.io/FastiShare/assets/fastishare-preview.png"
twitter_card: summary_large_image

# Favicon 
favicon: "https://flagodna-developer.github.io/FastiShare/assets/favicon.ico"
